[package]
name = "wg-mangler"
version = "0.1.1"
edition = "2024"
description = "a program used to obfuscate WireGuard message headers"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
clap = { version = "4.6.5", default-features = false, features = ["std", "derive", "help"] }
anyhow = "1.0.104"
log = "0.4.33"
bs58 = "0.5.1"
num_cpus = "1.17.0"
socket2 = "0.6.5"
env_logger = { version = "0.11.11", default-features = false }
getrandom = { version = "0.4.3", features = ["std"] }
sha2 = "0.11"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

